export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav className="bg-red-600 w-full">NavBar</nav>
        {children}
        <footer className="bg-lime-500">Footer</footer>
        </body>
    </html>
  )
}
